### ISSUE TITLE
We can't find the SAGNet in the model

### ISSUE THREAD

**Issue by yangwill81** [KevinDaldry/AANet#1]
Great Job! But we don't find the SAGNet in the network. Is there something wrong? Thanks.

**Comment by KevinDaldry** [comment]
Thanks for pointing it out.
SAGNet is the former-name of proposed AANet, and this project is uploaded before we decided to change its name.
I think you can simply replace the SAGNet by AANet to make it work. I will go through this project again to ensure the consistency of our network.
