### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by heikeyuhuajia** [KevinDaldry/AANet#2]
Hello author, thank you very much for your work. I have two doubts after executing the code on your github:
1. when I finished executing the TRAIN, the weights file was generated for 100 epochs, however, does the **F1 index** on the weights file **mean mean F1** or “**changed F1**”?
<img width="292" alt="image" src="https://github.com/KevinDaldry/AANet/assets/101233597/a22d4c50-27bc-4fbf-903d-e6773c8d7b1e">
2. also, I want to execute the test after I finish the training, and I see that you don't seem to have the test file in your repository, how can I run the test on the test set?
Thanks for your reply and good luck with your work!

**Comment by KevinDaldry** [comment]
Hello, glad to see your comments. I'm here to answer your questions. 
For Q1, I think you can consider it as 'changed F1', but I am not quite sure if I truly understand your definition of 'mean F1' and 'changed F1'. We calculate our F1 score based on the foreground predictions (TP), as the corresponding equation in our article indicates. I hope that I didn't misunderstand your meaning.
For Q2, we only put the main body of the project here to present our idea, so some files are not included. As it is a similar process to validate and test the model, you can adjust the validation process in 'train.py' to form your own 'test.py'.
